### ISSUE TITLE
Error In database initialization.

### ISSUE THREAD

**Issue by BalgopalPatro** [sumanbh/amazon-angular#26]
When i run the command ***yarn init:db*** then it shows the error that 

yarn run v1.19.1
$ node scripts/setupDatabase.js
Setting up the database...
error: password authentication failed for user "postgres"
Done in 0.59s.

**Comment by sumanbh** [comment]
You'll want to update the [config.json](https://github.com/sumanbh/node-amazon/blob/master/config/amazon.json#L10) with correct credentials for whatever postgres user you're using.

**Comment by BalgopalPatro** [comment]
Sir 
I changed my password and user name . But It Gives me the same error.
Please help me.

**Comment by sumanbh** [comment]
Can't really help you much more than that since it's related to your config. [This](https://github.com/sumanbh/node-amazon/blob/master/scripts/setupDatabase.js#L289) is where we pass the postgres config to [pg's Client](https://node-postgres.com/api/client), so you can try modifying it.
