### ISSUE TITLE
add an ORM? (sequelize)

### ISSUE THREAD

**Issue by bradoyler** [sumanbh/amazon-angular#9]
cool project.
Any interest in adding an ORM like https://www.npmjs.com/package/sequelize
Would be nice to use SQLite for easy dev setup.

**Comment by sumanbh** [comment]
I agree with using something like sequelize to create the database and automatically populate it. Will look into it. Also, I assume SQLite is a typo?

**Comment by bradoyler** [comment]
Not a typo http://www.sqlite.org

**Comment by sumanbh** [comment]
What purpose would SQLite serve? Unless you mean to use it instead of Postgres?

**Comment by bradoyler** [comment]
@sumanbh it's an approach I've seen before, to make the app is easier to setup for local development purposes. 

But that's probably not a great idea in the long run.

**Comment by sumanbh** [comment]
I added a simple script that sets up the database, and populates it. 

`yarn migrate` should do the trick.
